FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "sleep 2 && if [ -z \"$(ls -A alembic/versions/ 2>/dev/null)\" ]; then alembic revision --autogenerate -m initial; fi && alembic upgrade head && python seed_medicines.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]